CREATE TABLE [Mastermetadata].[Metadata] (

	[SourceSystem] varchar(255) NOT NULL, 
	[SourceSecretName] varchar(255) NULL, 
	[TableID] numeric NOT NULL, 
	[SubjectArea] varchar(255) NULL, 
	[SourceDBName] varchar(255) NULL, 
	[SourceSchema] varchar(255) NULL, 
	[SourceTableName] varchar(255) NULL, 
	[LoadType] varchar(255) NULL, 
	[IsActive] bit NOT NULL, 
	[Frequency] varchar(255) NULL, 
	[Bronze] varchar(255) NULL, 
	[Silver] varchar(255) NULL, 
	[Gold] varchar(255) NULL, 
	[DWHSchemaName] varchar(255) NULL, 
	[DWHTableName] varchar(255) NULL, 
	[ErrorLogPath] varchar(255) NULL, 
	[LastLoadDateColumn] varchar(255) NULL, 
	[MergeKey] varchar(255) NULL, 
	[DependencyTableIDs] varchar(255) NULL, 
	[LastLoadDateValue] varchar(255) NULL, 
	[PipelineEndTime] datetime2(3) NULL, 
	[PipelineStartTime] datetime2(3) NULL, 
	[PipelineRunStatus] varchar(255) NULL, 
	[Zone] varchar(255) NULL, 
	[StageCreateQuery] varchar(1000) NULL, 
	[NotebookName] varchar(255) NULL
);

