table 'Aging Range'
	lineageTag: eeb3c815-dcec-4d59-a065-7fa4535c24f3

	column 'Aging Range'
		dataType: string
		lineageTag: e6b9d880-169d-47b1-8142-3e3fdac54db7
		summarizeBy: none
		sourceColumn: Aging Range
		sortByColumn: 'Aging Flag'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column 'Aging Flag'
		dataType: int64
		formatString: 0
		lineageTag: 55f8aa5f-3dc1-4fee-af6c-96e2371d58c8
		summarizeBy: none
		sourceColumn: Aging Flag

		annotation SummarizationSetBy = Automatic

	partition 'Aging Range' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://avacorp1.sharepoint.com/sites/BusinessIntelligenceAnalytics/Shared%20Documents/Power%20BI%20Practice/Presales/Reporting%20Hub%20Dashboards/Finance/Account%20Payables/1.%20Define/Datapoints/Accounts%20Payables%20Report%20Datapoints.xlsx"), null, true),
				    #"Aging Range_Sheet" = Source{[Item="Aging Range",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Aging Range_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Aging Range", type text}, {"Aging Flag", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

