table 'Dim Date'
	lineageTag: 928088d9-dae5-468c-a2e5-536728274af5

	column Date
		dataType: dateTime
		formatString: dd-mm-yyyy
		lineageTag: 0a0969e2-3330-42e4-950a-2ba316002849
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 384f734d-7b45-4aad-bae3-473927e80ee6
			defaultHierarchy: LocalDateTable_26b9a8da-d17e-4f92-b08e-98a26469140b.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Month Name'
		dataType: string
		lineageTag: 87fa30aa-b349-4189-a133-64c2719e8f05
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 6947ac52-98c9-4c83-8f63-1fd3493b918c
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column Quarter
		dataType: string
		lineageTag: 88f7f696-1484-4144-b077-1292000fbf22
		summarizeBy: none
		sourceColumn: Quarter

		annotation SummarizationSetBy = Automatic

	column QuarterNumber
		dataType: int64
		formatString: 0
		lineageTag: 5f0ca9a8-6876-429e-b7bc-5783a0b3a699
		summarizeBy: sum
		sourceColumn: QuarterNumber

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: ae1e7aca-b490-4857-88a6-6bca96cdbd77
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	partition 'Dim Date' = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://avacorp1.sharepoint.com/sites/BusinessIntelligenceAnalytics/Shared%20Documents/Power%20BI%20Practice/Presales/Reporting%20Hub%20Dashboards/Finance/Account%20Payables/1.%20Define/Datapoints/Accounts%20Payables%20Report%20Datapoints.xlsx"), null, true),
				    #"Dim Date_Sheet" = Source{[Item="Dim Date",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(#"Dim Date_Sheet", [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Month Name", type text}, {"Month Number", Int64.Type}, {"Quarter", type text}, {"QuarterNumber", Int64.Type}, {"Year", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Exception

