table FactInvoice
	lineageTag: b239ef31-777f-4045-bd42-42541b4530f8

	column Company
		dataType: string
		lineageTag: 4791f7c9-b959-4d6d-a215-6125e93885d4
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column InvoiceNumber
		dataType: int64
		formatString: 0
		lineageTag: 136c8f1e-1772-4697-92ba-fe02b41c6830
		summarizeBy: sum
		sourceColumn: InvoiceNumber

		annotation SummarizationSetBy = Automatic

	column 'Invoice Date'
		dataType: dateTime
		formatString: dd-mm-yyyy
		lineageTag: 5f649313-01ad-41fc-b4d7-fca1df688b0d
		summarizeBy: none
		sourceColumn: Invoice Date

		variation Variation
			isDefault
			relationship: 0d5df426-bb4a-4a01-b664-d9b7d7f886eb
			defaultHierarchy: LocalDateTable_a9f8aef1-55af-46dd-9c13-bc68f0034d6d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column DueDate
		dataType: dateTime
		formatString: dd-mm-yyyy
		lineageTag: 06103b8d-41ac-4eb3-a48d-9b74f3818f6c
		summarizeBy: none
		sourceColumn: DueDate

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column 'Payment Date'
		dataType: dateTime
		formatString: dd-mm-yyyy
		lineageTag: 97b721db-63ae-4294-aab9-3bc225720aee
		summarizeBy: none
		sourceColumn: Payment Date

		variation Variation
			isDefault
			relationship: 3e1d17fd-5615-44e6-8839-029aeda5f222
			defaultHierarchy: LocalDateTable_e87f8299-69ec-4e1b-bd56-650735166c49.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column BalanceDue
		dataType: int64
		formatString: 0
		lineageTag: c99fd32c-0d7f-4df5-bed0-ecac87d0cd8b
		summarizeBy: sum
		sourceColumn: BalanceDue

		annotation SummarizationSetBy = Automatic

	column 'Payment Status'
		dataType: string
		lineageTag: eba29e97-4d19-40d0-a4f2-3b3ab4f3ee17
		summarizeBy: none
		sourceColumn: Payment Status

		annotation SummarizationSetBy = Automatic

	column 'Open / Closed'
		dataType: string
		lineageTag: 3ab99179-e7f6-493d-87d7-138d0ebcbfc8
		summarizeBy: none
		sourceColumn: Open / Closed

		annotation SummarizationSetBy = Automatic

	column 'Aging Range'
		dataType: string
		lineageTag: dffb4b8e-e06c-4d83-bc76-5eaa61f4f50c
		summarizeBy: none
		sourceColumn: Aging Range

		annotation SummarizationSetBy = Automatic

	column 'Carrier / Vendor'
		dataType: string
		lineageTag: b03733c7-21a7-411f-8d50-351d672f9239
		summarizeBy: none
		sourceColumn: Carrier / Vendor

		annotation SummarizationSetBy = Automatic

	column 'Agent Name'
		dataType: string
		lineageTag: 34237fad-5934-4a3d-b563-989500d6f7bf
		summarizeBy: none
		sourceColumn: Agent Name

		annotation SummarizationSetBy = Automatic

	column CarrierInvoiceAmount
		dataType: double
		lineageTag: d25790f5-878b-4371-99d0-34f70f8890b2
		summarizeBy: sum
		sourceColumn: CarrierInvoiceAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column PaidAmount
		dataType: double
		lineageTag: a37be31f-b1a8-462e-9f05-8ac7ca27d1fc
		summarizeBy: sum
		sourceColumn: PaidAmount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CurrentAmount
		dataType: int64
		formatString: 0
		lineageTag: 7df662a4-30b5-40f4-a60b-5ec9b8727ae6
		summarizeBy: sum
		sourceColumn: CurrentAmount

		annotation SummarizationSetBy = Automatic

	column NonCurrentAmount
		dataType: int64
		formatString: 0
		lineageTag: 3605c811-6f3d-4a16-8c19-42851154c776
		summarizeBy: sum
		sourceColumn: NonCurrentAmount

		annotation SummarizationSetBy = Automatic

	column 'Invoice Status'
		dataType: string
		lineageTag: 97274f13-e8e4-4d29-881d-499f674ce4bf
		summarizeBy: none
		sourceColumn: Invoice Status

		annotation SummarizationSetBy = Automatic

	column Mode
		dataType: string
		lineageTag: 14d9c1d6-79c2-4daa-9ee6-a1c4d941f9b1
		summarizeBy: none
		sourceColumn: Mode

		annotation SummarizationSetBy = Automatic

	column COGS
		dataType: double
		lineageTag: 377ab55a-4f0a-40ab-9e33-2342e4ff4dd0
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Closure Days' =
			
			IF(
			    FactInvoice[Open / Closed] = "Closed",
			        DATEDIFF(FactInvoice[Invoice Date], FactInvoice[Payment Date], DAY),  0
			)
		formatString: 0
		lineageTag: 8e495a39-9709-4c6b-a296-1e46c376d0cd
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Aging Flag'
		dataType: string
		lineageTag: 8961b6f7-a9b7-4ee5-9b4e-c21f5e63dab5
		summarizeBy: none
		sourceColumn: Aging Flag

		annotation SummarizationSetBy = Automatic

	partition FactInvoice = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://avacorp1.sharepoint.com/sites/BusinessIntelligenceAnalytics/Shared%20Documents/Power%20BI%20Practice/Presales/Reporting%20Hub%20Dashboards/Finance/Account%20Payables/1.%20Define/Datapoints/Accounts%20Payables%20Report%20Datapoints.xlsx"), null, true),
				    FactInvoice_Sheet = Source{[Item="FactInvoice",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(FactInvoice_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company", type text}, {"InvoiceNumber", Int64.Type}, {"Invoice Date", type date}, {"DueDate", type date}, {"Payment Date", type date}, {"BalanceDue", Int64.Type}, {"Payment Status", type text}, {"Open / Closed", type text}, {"Aging Range", type any}, {"Carrier / Vendor", type text}, {"Agent Name", type text}, {"CarrierInvoiceAmount", type number}, {"PaidAmount", type number}, {"CurrentAmount", Int64.Type}, {"NonCurrentAmount", Int64.Type}, {"Invoice Status", type text}, {"Mode", type text}, {"COGS", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type"," 01-30","1-30",Replacer.ReplaceValue,{"Aging Range"})
				in
				    #"Replaced Value"

	annotation PBI_ResultType = Table

